import type { NextPage } from 'next';
import { useState, useEffect } from "react";
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Products from "../components/products";


const Home: NextPage = ({ data }) => {
  const [grid, setGrid] = useState('grid');

  function handleSwitchGrid(value: string) {
    setGrid(value)
  }

  console.log('data', data)

  function SwitchGrid (grid: string) {
    switch (grid) {
      case 'grid2':
        return 'grid grid-cols-1 gap-y-10 gap-x-6  xl:gap-x-8  sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-2'
      case 'grid3':
        return 'grid grid-cols-1 gap-y-10 gap-x-6  xl:gap-x-8   sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-3'
      case 'grid4':
        return 'grid grid-cols-1 gap-y-10 gap-x-6  xl:gap-x-8   sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'
      case 'grid5':
        return 'grid grid-cols-1 gap-y-10 gap-x-6  xl:gap-x-8   sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5'
      default:
        return ' grid grid-cols-1 gap-y-10 gap-x-6  xl:gap-x-8  sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'
    }
  }

  function fetchProducts() {
    fetch('https://fakestoreapi.com/products/1')
            .then(res=>res.json())
            .then(json=>console.log(json))
  }


  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={() => handleSwitchGrid("grid2")}>Grid 2</button>
      <button onClick={() => handleSwitchGrid("grid3")}>Grid 3</button>
      <button onClick={() => handleSwitchGrid("grid4")}>Grid 4</button>

      <div className="bg-white">
        <div className={'mx-auto max-w-2xl py-16 px-4 sm:py-24 sm:px-6 lg:max-w-7xl lg:px-8'}>
        

        <div className="flex flex-row justify-between">
            <h2 className="">Products</h2>
            <div>
                <button onClick={() => handleSwitchGrid("grid2")}>Grid 2</button>
                <button onClick={() => handleSwitchGrid("grid3")}>Grid 3</button>
                <button onClick={() => handleSwitchGrid("grid4")}>Grid 4</button>
            </div>
        </div>

         <div className={SwitchGrid(grid)}>
          {data && data.map((item: any, index: number) => (<>
              <Products item={item} index={index} />
          </>))}
            
        </div>
      </div>


    </div>
    </div>
  )
}

export async function getStaticProps() {
  // Fetch data from external API
  const res = await fetch(`https://fakestoreapi.com/products`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}

export default Home
